# 生产环境配置
server:
  port: 8081

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://www.haobingo.space:3306/haobingo_master?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
